name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version-file: example/pubspec.yaml
          channel: 'stable'
          architecture: x64
      - run: flutter --version
      - run: flutter pub get
      
      

      - run: pod repo update
        working-directory: example/ios

      - name: Update CocoaPods
        run: pod repo update
        working-directory: example/ios
        

      - run: flutter build ios --release --no-codesign
        working-directory: example
      - run: codesign --force --entitlements ios/Runner/Runner.entitlements --sign - build/ios/iphoneos/Runner.app
        working-directory: example
    

      - run: mkdir Payload
        working-directory: example/build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: example/build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: example/build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: example/build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
